Add compliant and noncompliant examples of javascript/file-and-directory-information-exposure@v1.0
aws-samples/amazon-codeguru-reviewer-javascript-detectors pull request #27
Opened 2023-02-24 08:53 UTC by ankit-amazon

*Description of changes:*
* Rules Added: javascript/file-and-directory-information-exposure@v1.0
* Added new functions for compliant and non compliant examples
* Added .gitignore

2023-02-28 18:59 UTC, ctlai95 requested changes

2023-02-28 18:59 UTC, ctlai95 commented on src/javascript/detectors/file_and_directory_information_exposure/file_and_directory_information_exposure.js
> +    var serveStaticMiddleware = serveStatic('public', { index : false, dotfiles : 'allow' })
```suggestion
    var serveStaticMiddleware = serveStatic('public', { index: false, dotfiles: 'allow' })
```

2023-03-01 04:28 UTC, ankit-amazon commented on src/javascript/detectors/file_and_directory_information_exposure/file_and_directory_information_exposure.js
> +    var serveStaticMiddleware = serveStatic('public', { index : false, dotfiles : 'allow' })
Improved example.

2023-03-02 01:11 UTC, ctlai95 approved these changes

2023-03-02 18:53 UTC, merged