Add compliant and noncompliant examples of javascript/cross-site-scripting@v1.0
aws-samples/amazon-codeguru-reviewer-javascript-detectors pull request #29
Opened 2023-02-24 09:50 UTC by ankit-amazon

*Description of changes:*
* Rules Added: javascript/cross-site-scripting@v1.0
* Added new functions for compliant and non compliant examples
* Added .gitignore

2023-02-28 03:24 UTC, shikele commented on src/javascript/detectors/cross_site_scripting/cross_site_scripting.js
> +
should we include `require('node-esapi')` here to make example self contained? Might have to change `const` to `var`

2023-02-28 18:47 UTC, ctlai95 requested changes

2023-02-28 18:47 UTC, ctlai95 commented on src/javascript/detectors/cross_site_scripting/cross_site_scripting.js
> +    let url = $(location).attr('hash').slice(1)
For consistency, can we use the same method of extracting the URL between the two examples? It looks like one is from the window object search params and the other is from hash params using jQuery.

2023-02-28 18:47 UTC, ctlai95 commented on src/javascript/detectors/cross_site_scripting/cross_site_scripting.js
> +    $.ajax(url)
Should we add `data: "Hello"` here as well?

2023-03-02 18:47 UTC, mj632 approved these changes

2023-03-02 18:47 UTC, merged