Add compliant and noncompliant examples of javascript/sensitive-information-leak@v1.0
aws-samples/amazon-codeguru-reviewer-javascript-detectors pull request #48
Opened 2023-02-24 13:48 UTC by swaraj-amazon

*Description of changes:*
* Rules Added: javascript/sensitive-information-leak@v1.0
* Added new functions for compliant and non compliant examples

2023-02-27 18:51 UTC, ctlai95 requested changes

2023-02-28 10:16 UTC, swaraj-amazon commented on src/javascript/detectors/sensitive_information_leak/sensitive_information_leak.js
> +            // Non-Compliant: sets the policy as no-referrer-when-downgrade.
Updatesd

2023-02-28 10:40 UTC, swaraj-amazon commented on package.json
> +  "homepage": "https://github.com/swaraj-amazon/amazon-codeguru-reviewer-javascript-detectors#readme"
Updates the URLs

2023-02-28 18:26 UTC, ctlai95 approved these changes

2023-03-02 18:33 UTC, merged