Add compliant and noncompliant examples of javascript/insecure-temp-file@v1.0
aws-samples/amazon-codeguru-reviewer-javascript-detectors pull request #53
Opened 2023-02-28 11:26 UTC by Kamlesh-Gour

*Description of changes:*
* Rules Added: insecure-temp-file@v1.0
* Added new functions for compliant and non compliant examples
* Added .gitignore

2023-02-28 18:56 UTC, ctlai95 requested changes

2023-02-28 18:56 UTC, ctlai95 commented on src/detectors/insecure_temporary_file/insecure_temporary_file.js
> +    // Compliant: tmp library to securely create or read a temporary files.
```suggestion
    // Compliant: tmp library to securely create or read temporary files.
```

2023-02-28 18:56 UTC, ctlai95 commented on src/detectors/insecure_temporary_file/insecure_temporary_file.js
> +    // Noncompliant: the global directory path is given for opening a file or creating a file the case can be vulnerable to injection attacks.
```suggestion
    // Noncompliant: the global directory path is given for opening a file or creating a file which can be vulnerable to injection attacks.
```

2023-03-01 05:10 UTC, Kamlesh-Gour commented on src/detectors/insecure_temporary_file/insecure_temporary_file.js
> +    // Noncompliant: the global directory path is given for opening a file or creating a file the case can be vulnerable to injection attacks.
Updated

2023-03-01 05:10 UTC, Kamlesh-Gour commented on src/detectors/insecure_temporary_file/insecure_temporary_file.js
> +    // Compliant: tmp library to securely create or read a temporary files.
Updated

2023-03-02 18:49 UTC, mj632 approved these changes

2023-03-02 18:49 UTC, merged